# Generated by Django 5.2.17 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='staff_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
